/* LS01-LS10 chemical registry. variable=true means representative structure. */
window.CHEMICALS=[
["Phthalsäureanhydrid","邻苯二甲酸酐","PSA",1,"Säureanhydrid","O=C1OC(=O)c2ccccc12"],["Isophthalsäure","间苯二甲酸","IPS",1,"Dicarbonsäure","O=C(O)c1cccc(C(=O)O)c1"],["Terephthalsäure","对苯二甲酸","TPS",1,"Dicarbonsäure","O=C(O)c1ccc(C(=O)O)cc1"],["Maleinsäureanhydrid","马来酸酐","MSA",1,"Säureanhydrid","O=C1OC(=O)C=C1"],["Adipinsäure","己二酸","ADS",1,"Dicarbonsäure","O=C(O)CCCCC(=O)O"],
["Ethylenglykol","乙二醇","EG",1,"Diol","OCCO"],["Propylenglykol-1,2","1,2-丙二醇","PG",1,"Diol","CC(O)CO"],["Neopentylglykol","新戊二醇","NPG",1,"Diol","OCC(C)(C)CO"],["Butandiol-1,4","1,4-丁二醇","BDO",1,"Diol","OCCCCO"],["Diethylenglykol","二甘醇","DEG",1,"Etherdiol","OCCOCCO"],["Dipropylenglykol","二丙二醇","DPG",1,"Etherdiol","CC(O)COCC(C)O",true],["Hexandiol-1,6","1,6-己二醇","HDO",1,"Diol","OCCCCCCO"],["Cyclohexandimethanol","环己烷二甲醇","CHDM",1,"Diol","OCC1CCC(CO)CC1"],
["Trimethylolpropan","三羟甲基丙烷","TMP",1,"Triol","CCC(CO)(CO)CO"],["Glycerin","甘油","",1,"Triol","OCC(O)CO"],["Pentaerythrit","季戊四醇","",1,"Tetrol","OCC(CO)(CO)CO"],["ε-Caprolacton","ε-己内酯","",1,"Lacton","O=C1OCCCCC1"],["Hydroxystearinsäure","羟基硬脂酸","",1,"Hydroxycarbonsäure","CCCCCCCCCCCCC(O)CCCC(=O)O",true],["Xylol","二甲苯","",1,"Schleppmittel","Cc1ccccc1C",true],["Cyclohexan","环己烷","",1,"Schleppmittel","C1CCCCC1"],["Tetrabutyltitanat","钛酸四丁酯","TBT",1,"Katalysator","CCCCO[Ti](OCCCC)(OCCCC)OCCCC"],["Dibutylzinnoxid","二丁基氧化锡","DBTO",1,"Katalysator","CCCC[Sn](CCCC)=O"],
["Laurinsäure","月桂酸","",2,"Fettsäure","CCCCCCCCCCCC(=O)O"],["Stearinsäure","硬脂酸","",2,"Fettsäure","CCCCCCCCCCCCCCCCCC(=O)O"],["Ölsäure","油酸","",2,"Fettsäure","CCCCCCCCC=CCCCCCCCC(=O)O"],["Linolsäure","亚油酸","",2,"Fettsäure","CCCCCC=CCC=CCCCCCCCC(=O)O"],["Linolensäure","亚麻酸","",2,"Fettsäure","CCC=CCC=CCC=CCCCCCCCC(=O)O"],["Ricinolsäure","蓖麻油酸","",2,"Hydroxyfettsäure","CCCCCC(O)CC=CCCCCCCCC(=O)O"],["Cobaltoctoat","异辛酸钴（代表络合物）","",2,"Sikkativ","[Co](OC(=O)C(CC)CCCC)(OC(=O)C(CC)CCCC)",true],
["Melamin","三聚氰胺","",3,"Amidbaustein","Nc1nc(N)nc(N)n1"],["Harnstoff","尿素","",3,"Amidbaustein","NC(=O)N"],["Formaldehyd","甲醛","",3,"Aldehyd","C=O"],["Methanol","甲醇","",3,"Veretherungsalkohol","CO"],["n-Butanol","正丁醇","",3,"Veretherungsalkohol","CCCCO"],["Benzoguanamin","苯并胍胺","",3,"Amidbaustein","Nc1nc(N)nc(c2ccccc2)n1"],["Glycoluril","甘脲","",3,"Amidbaustein","O=C1NC2NC(=O)NC2N1"],["Hexamethoxymethylmelamin","六甲氧甲基三聚氰胺","HMMM",3,"Vernetzer","COCN1C(OC)N(COC)C(=N(COC)C(OC)N1COC)",true],["Salzsäure","盐酸","HCl",3,"Säurekatalysator","Cl"],["Salpetersäure","硝酸","HNO₃",3,"Säurekatalysator","O=N(=O)O"],["p-Toluolsulfonsäure","对甲苯磺酸","p-TSA",3,"Säurekatalysator","Cc1ccc(S(=O)(=O)O)cc1"],
["Methylmethacrylat","甲基丙烯酸甲酯","MMA",4,"Monomer","CC(=C)C(=O)OC"],["Butylacrylat","丙烯酸丁酯","BA",4,"Monomer","CCCCOC(=O)C=C"],["Styrol","苯乙烯","",4,"Monomer","C=Cc1ccccc1"],["2-Hydroxyethylmethacrylat","甲基丙烯酸羟乙酯","HEMA",4,"OH-Monomer","CC(=C)C(=O)OCCO"],["Acrylsäure","丙烯酸","AS",4,"COOH-Monomer","C=CC(=O)O"],["Methacrylsäure","甲基丙烯酸","MAS",4,"COOH-Monomer","CC(=C)C(=O)O"],["Benzoylperoxid","过氧化苯甲酰","BPO",4,"Initiator","O=C(OOC(=O)c1ccccc1)c2ccccc2"],["Azobisisobutyronitril","偶氮二异丁腈","AIBN",4,"Initiator","N#CC(C)(C)N=NC(C)(C)C#N"],["Dodecylmercaptan","十二烷基硫醇","",4,"Regler","CCCCCCCCCCCCS"],
["Hexamethylendiisocyanat","六亚甲基二异氰酸酯","HDI",5,"Diisocyanat","O=C=NCCCCCCN=C=O"],["Toluylendiisocyanat","甲苯二异氰酸酯","TDI",5,"Diisocyanat","Cc1cc(N=C=O)ccc1N=C=O",true],["Diphenylmethandiisocyanat","二苯基甲烷二异氰酸酯","MDI",5,"Diisocyanat","O=C=Nc1ccc(Cc2ccc(N=C=O)cc2)cc1"],["Isophorondiisocyanat","异佛尔酮二异氰酸酯","IPDI",5,"Diisocyanat","CC1(C)CC(N=C=O)CC(C)(CN=C=O)C1",true],["Wasser","水","H₂O",5,"Nebenreaktant","O"],["Dibutylzinndilaurat","二月桂酸二丁基锡","DBTL",5,"Katalysator","CCCC[Sn](CCCC)(OC(=O)CCCCCCCCCCC)OC(=O)CCCCCCCCCCC"],
["Dimethylolpropionsäure","二羟甲基丙酸","DMPA",6,"Ionomer","CC(CO)(CO)C(=O)O"],["Triethylamin","三乙胺","TEA",6,"Neutralisationsbase","CCN(CC)CC"],["Ethylendiamin","乙二胺","EDA",6,"Kettenverlängerer","NCCN"],["Benzotriazol-UV-Absorber","苯并三唑型UV吸收剂（代表）","",7,"UV-Absorber","Oc1ccc2nnnc2c1",true],
["Natriumdodecylsulfat","十二烷基硫酸钠","SDS",8,"Emulgator","CCCCCCCCCCCCOS(=O)(=O)[O-].[Na+]"],["Natriumperoxodisulfat","过二硫酸钠","",8,"Initiator","[Na+].[Na+].[O-]S(=O)(=O)OOS(=O)(=O)[O-]"],
["Titandioxid","二氧化钛","TiO₂",9,"Pigment","O=[Ti]=O"],["Calciumcarbonat","碳酸钙","CaCO₃",9,"Füllstoff","[Ca+2].[O-]C(=O)[O-]"],["Bariumsulfat","硫酸钡","BaSO₄",9,"Füllstoff","[Ba+2].[O-]S(=O)(=O)[O-]"],["Ammoniak","氨","NH₃",9,"Base","N"],
["Bisphenol A","双酚A","BPA",10,"Epoxidbaustein","CC(C)(c1ccc(O)cc1)c2ccc(O)cc2"],["Epichlorhydrin","环氧氯丙烷","ECH",10,"Epoxidbaustein","ClCC1CO1"],["Bisphenol-A-diglycidylether","双酚A二缩水甘油醚","BADGE",10,"Epoxidharz","CC(C)(c1ccc(OCC2CO2)cc1)c3ccc(OCC4CO4)cc3"],["Diethylentriamin","二乙烯三胺","DETA",10,"Aminhärter","NCCNCCN"],["Methylisobutylketon","甲基异丁基酮","MIBK",10,"Lösemittel","CC(=O)CC(C)C"],["Methylethylketon","甲乙酮","MEK",10,"Lösemittel","CC(=O)CC"],["Phenol","苯酚","",10,"Phenolharzbaustein","Oc1ccccc1"],["Essigsäure","乙酸","",10,"Neutralisationssäure","CC(=O)O"],["Ameisensäure","甲酸","",10,"Neutralisationssäure","C(=O)O"],
["Polyester-Wiederholungseinheit","聚酯重复单元","",1,"Polymer","OCCOC(=O)CCCCC(=O)",true],["Alkydharz-Segment","醇酸树脂代表链段","",2,"Polymer","CCCCC=CCCCCC(=O)OCC(CO)COC(=O)c1ccccc1C(=O)O",true],["Melaminharz-Netzwerkfragment","三聚氰胺树脂网络片段","",3,"Polymer","COCN1C(OC)N(COC)C(=N(COC)C(OC)N1COC)",true],["Poly(methylmethacrylat)-Dimer","聚甲基丙烯酸甲酯代表二聚单元","PMMA",4,"Polymer","CC(C)(C(=O)OC)CC(C)(C(=O)OC)C",true],["OH-Acrylat-Copolymersegment","含OH丙烯酸共聚物代表链段","",4,"Polymer","CC(C)(C(=O)OC)CC(C)(C(=O)OCCO)C",true],["Polyurethan-Wiederholungseinheit","聚氨酯代表重复单元","PUR",6,"Polymer","OCCOC(=O)NCCCCCCNC(=O)",true],["Polyacrylsäure-Dimer","聚丙烯酸代表二聚单元","PAA",8,"Polymer","CC(C(=O)O)CC(C(=O)O)C",true],["Polyvinylchlorid-Dimer","聚氯乙烯代表二聚单元","PVC",9,"Polymer","CC(Cl)CC(Cl)C",true],["Epoxid-Amin-Netzwerkfragment","环氧-胺网络片段","",10,"Polymer","OCC(NCCNCCN)CO",true],["Phenol-Formaldehyd-Fragment","酚醛树脂代表链段","",10,"Polymer","Oc1ccc(Cc2ccc(O)cc2)cc1",true],
["Zink-2-ethylhexanoat","异辛酸锌（代表络合物）","Zinkoctoat",1,"Katalysator","[Zn](OC(=O)C(CC)CCCC)OC(=O)C(CC)CCCC",true],["Lithium-2-ethylhexanoat","异辛酸锂","Lithiumoctoat",2,"Sikkativ","[Li+].[O-]C(=O)C(CC)CCCC"],["Carbaminsäure","氨基甲酸","",5,"Zwischenprodukt","NC(=O)O"],["Kohlendioxid","二氧化碳","CO₂",5,"Nebenprodukt","O=C=O"],["Harnstoffbindung-Fragment","脲键代表片段","",5,"Reaktionsprodukt","CNC(=O)NC",true],["β-Hydroxyamin-Fragment","β-羟基胺中间产物","",10,"Reaktionsprodukt","NCCO",true],
["Trimellithsäureanhydrid","偏苯三酸酐","TMSA",1,"Säureanhydrid","O=C1OC(=O)c2cc(C(=O)O)ccc12"],["Tetrahydrophthalsäureanhydrid","四氢邻苯二甲酸酐","THPSA",1,"Säureanhydrid","O=C1OC(=O)C2CC=CCC12"],["Hexahydrophthalsäureanhydrid","六氢邻苯二甲酸酐","HHPSA",1,"Säureanhydrid","O=C1OC(=O)C2CCCCC12"],["2-Methylpropandiol-1,3","2-甲基-1,3-丙二醇","MPD",1,"Diol","CC(CO)CO"],["2,2,4-Trimethylpentandiol-1,3","2,2,4-三甲基-1,3-戊二醇","TMPD",1,"Diol","CC(C)CC(O)C(C)(C)CO"],["Hydroxypivalinsäure-neopentylglykolester","羟基新戊酸新戊二醇酯","HPN",1,"Hydroxyester","CC(C)(CO)COC(=O)C(C)(C)CO"],["Di-Trimethylolpropan","双三羟甲基丙烷","Di-TMP",1,"Polyol","CCC(CO)(CO)COCC(CO)(CO)CC"],["Trishydroxyethylisocyanurat","三羟乙基异氰尿酸酯","THEIC",1,"Polyol","OCCN1C(=O)N(CCO)C(=O)N(CCO)C1=O"],["Butandioldiglycidylether","丁二醇二缩水甘油醚","",1,"Reaktivverdünner","C1CO1COCCCCOCC2CO2"],
["Palmitinsäure","棕榈酸","",2,"Fettsäure","CCCCCCCCCCCCCCCC(=O)O"],["Isononansäure","异壬酸（代表异构体）","",2,"Fettsäure","CC(C)CCCCCC(=O)O",true],["Abietinsäure","松香酸","",2,"Harzsäure","CC1=CCC2(C)C(C1)C1(C)CCC(C(C)C(=O)O)=C1C2",true],
["Butylmethacrylat","甲基丙烯酸丁酯","BMA",4,"Monomer","CCCCOC(=O)C(=C)C"],["Ethylacrylat","丙烯酸乙酯","EA",4,"Monomer","CCOC(=O)C=C"],["Hydroxypropylmethacrylat","甲基丙烯酸羟丙酯","HPMA",4,"OH-Monomer","CC(=C)C(=O)OCCCO",true],["Isopropanol","异丙醇","IPA",4,"Lösemittel","CC(O)C"],["Butylglykol","乙二醇单丁醚","EGBE",4,"Lösemittel","CCCCOCCO"],
["Methyl­ethanolamin","甲基乙醇胺","MEOLA",10,"Amin","CNCCO"],["Diethanolamin","二乙醇胺","DEA",10,"Amin","OCCNCCO"],["Triethanolamin","三乙醇胺","TEA",10,"Amin","OCCN(CCO)CCO"],["m-Xylilendiamin","间苯二甲胺","MXDA",10,"Aminhärter","NCCc1cccc(CN)c1"],["Schwefelsäure","硫酸","H₂SO₄",9,"Säure","OS(=O)(=O)O"],["Phosphorsäure","磷酸","H₃PO₄",9,"Säure","OP(=O)(O)O"]
].map((x,i)=>({id:"chem-"+(i+1),name:x[0],zh:x[1],abbr:x[2],ls:x[3],role:x[4],smiles:x[5],variable:!!x[6]}));
