/* 前10章：每章5组、每组5层，共50组/250层。机理图依据课件反应重新整理。 */
const WC=[
// LS01 Polyester
[1,"Warum kann aus Diol und Dicarbonsäure ein Polymer entstehen?",["Beide Monomere besitzen mindestens zwei reaktive Gruppen.","Jede Reaktion erzeugt eine Esterbindung und lässt weitere Endgruppen übrig.","Dadurch reagieren zunächst Dimere, dann Oligomere und schließlich lange Ketten.","Hohe Molmasse entsteht erst bei sehr hohem Umsatz und nahezu ausgeglichener Stöchiometrie.","Schon wenig monofunktioneller Stoff oder stöchiometrischer Überschuss begrenzt nach Carothers die Kettenlänge."],"Nicht jede Esterbildung ist schon eine Polykondensation.","R–(OH)₂ + R'–(COOH)₂\n       ↓ wiederholte Veresterung\nHO–[R–O–C(=O)–R'–C(=O)–O]ₙ–R–OH + H₂O"],
[1,"Wie erfolgt die säurekatalysierte Veresterung mechanistisch?",["Zuerst wird der Carbonyl-Sauerstoff der Carbonsäure protoniert.","Dadurch wird das Carbonyl-C stärker elektrophil.","Das freie Elektronenpaar :O: des Alkohols greift dieses C an; ein tetraedrisches Oxonium-Zwischenprodukt entsteht.","Nach Protonenumlagerung wird eine OH-Gruppe zu H₂O als guter Abgangsgruppe.","Wasser tritt aus, die C=O-Bindung bildet sich zurück und Deprotonierung liefert den Ester."],"Der Katalysator wird regeneriert; er verschiebt das Gleichgewicht nicht.","1  R–C(=O)–OH + H⁺ → R–C(=OH⁺)–OH\n2  HO:–R'  ↷ C=O ; π(C=O) ↷ O\n              OH\n             /\n   R–C–OH            tetraedrisches Intermediat\n       \\O⁺H–R'\n3  Protonentransfer: –OH → –OH₂⁺\n4  :O: ↷ C ; C–OH₂⁺ ↷ O → R–C(=O)–O⁺H–R' + H₂O\n5  Deprotonierung → R–C(=O)–O–R' + H⁺"],
[1,"Wie öffnet ein Alkohol ein Carbonsäureanhydrid?",["Das Alkohol-O besitzt ein freies Elektronenpaar und ist nucleophil.","Es greift eines der beiden elektrophilen Anhydrid-Carbonyl-C-Atome an.","Die C=O-π-Bindung klappt auf und ein tetraedrisches Zwischenprodukt entsteht.","Beim Rückklappen der O⁻-Elektronen wird die Anhydrid-C–O-Bindung gespalten; Carboxylat geht ab.","Protonentransfer liefert Halbester und Carbonsäure; zunächst entsteht dabei kein Wasser."],"Anhydridöffnung und klassische Säure/Alkohol-Veresterung sind nicht derselbe Einzelschritt.","          O                 O⁻\n          ║                /\nR–OH  +  R'–C–O–C(=O)–R'  →  R'–C–O⁺H–R\n  :O: ↷ C=O ; π ↷ O             \\O–C(=O)–R'\n\nO⁻ ↷ C ; C–O(Anhydrid) ↷ O\n→ R'–C(=O)–O–R  +  ⁻O–C(=O)–R'\n→ Protontransfer → Halbester + R'–COOH"],
[1,"Warum werden Wasser, Säurezahl und Viskosität gleichzeitig verfolgt?",["Wasseranfall zeigt unmittelbar, dass Kondensationsschritte stattfinden.","Die Säurezahl zeigt den Verbrauch freier COOH-Gruppen.","Viskosität steigt mit Molmassenaufbau und Verzweigung.","Keiner dieser Werte allein beweist die gewünschte Molekülarchitektur.","Gemeinsam erlauben sie, Umsatz, Molmassenaufbau und Gelrisiko zu beurteilen."],"Säurezahl ist kein direkter Ersatz für GPC-Molmasse.","COOH + OH → Ester + H₂O↑\nSZ ↓  |  η ↑  |  Destillatmenge ↑"],
[1,"Warum werden NPG und TMP gemeinsam zur Polyesterentwicklung eingesetzt?",["NPG ist difunktionell und baut überwiegend Kettensegmente auf.","Seine abgeschirmte Struktur verbessert häufig Hydrolyse- und Wetterbeständigkeit.","TMP besitzt drei OH-Gruppen und erzeugt Verzweigung.","Verzweigung erhöht Zahl verfügbarer OH-Vernetzungsstellen.","Zu viel TMP erhöht Viskosität und kann den Gelpunkt bereits im Reaktor überschreiten."],"NPG und TMP erfüllen unterschiedliche Aufgaben: Segmentaufbau versus Funktionalität.","NPG: HO–CH₂–C(CH₃)₂–CH₂–OH\nTMP: HO–CH₂–C(CH₂OH)₂–CH₂–CH₃\n                    │\nlineare Segmente + Verzweigung → OH-funktioneller Polyester"],
// LS02 Alkyd
[2,"Warum ist ein Alkydharz weiterhin ein Polyester?",["Das Grundgerüst entsteht aus Polyolen und Polycarbonsäuren.","Diese Bausteine werden durch Esterbindungen verknüpft.","Fettsäuren sind nur ein zusätzlicher monofunktioneller Modifikator.","Sie hängen als lange Seitenketten beziehungsweise Endgruppen am Polyestergerüst.","Ungesättigte Fettsäurereste ermöglichen anschließend oxidative Vernetzung."],"Eine Fettsäure allein kann kein polymeres Alkydgerüst bilden.","Polyester–OH + HOOC–Fettsäure → Polyester–O–C(=O)–Fettsäure + H₂O"],
[2,"Wie beginnt die oxidative Vernetzung eines Alkydharzes?",["Luftsauerstoff erreicht die ungesättigten Fettsäurereste.","Ein allylisches H wird abstrahiert und ein resonanzstabilisiertes C-Radikal entsteht.","O₂ addiert sehr schnell und bildet ein Peroxyradikal ROO•.","Dieses abstrahiert H von einer Nachbarkette und bildet Hydroperoxid ROOH.","Metall-Sikkative spalten ROOH in Radikale, die Ketten über C–C- oder C–O–C-Bindungen vernetzen."],"Oxidative Trocknung ist eine radikalische chemische Vernetzung, keine bloße Verdunstung.","–CH=CH–CH₂– + •X → –CH=CH–CH•– + XH\nR• + O₂ → ROO•\nROO• + RH → ROOH + R•\nROOH --Co/Mn→ RO• + •OH\nR• + •R → R–R   /   RO• + •R → R–O–R"],
[2,"Warum sagt die Iodzahl etwas über Trocknung aus?",["Iod addiert an C=C-Doppelbindungen.","Der Iodverbrauch misst deshalb den Ungesättigtheitsgrad eines Öls.","Mehr geeignete Doppelbindungen bedeuten mehr allylische Angriffspunkte.","Dadurch können mehr Peroxide und Vernetzungsstellen entstehen.","Sehr hohe Ungesättigtheit kann aber Oxidation, Vergilbung und Alterung beschleunigen."],"Iodzahl beschreibt Potenzial, nicht allein reale Trocknungsgeschwindigkeit.","C=C + I₂ → –C(I)–C(I)–\nIodzahl = g I₂ / 100 g Öl"],
[2,"Warum beeinflusst die Öllänge Härte und Flexibilität?",["Mehr Öl bedeutet mehr lange aliphatische Fettsäurereste.","Diese flexiblen Ketten erhöhen Segmentbeweglichkeit und senken meist Tg.","Gleichzeitig wird der starre Polyesteranteil pro Masse kleiner.","Lange Alkydharze sind daher meist flexibler und besser löslich.","Kurze Alkydharze sind härter und werden häufiger fremdvernetzt."],"Öllänge und Anzahl reaktiver Doppelbindungen sind verschiedene Größen.","kurz: viel Polyester / wenig Öl → härter\nlang: wenig Polyester / viel Öl → flexibler"],
[2,"Warum muss ein Sikkativpaket Oberflächen- und Durchtrocknung ausgleichen?",["O₂ steht zuerst an der Oberfläche zur Verfügung.","Sehr aktive Primärtrockner erzeugen dort schnell Radikale und eine Haut.","Diese Haut kann O₂-Diffusion in tiefere Schichten behindern.","Unter der Haut bleibt weiches Material und später entstehen Runzeln.","Kombinierte Primär-, Durchtrockner und Hilfstrockner verteilen die Reaktion über die Filmdicke."],"Mehr Cobalt bedeutet nicht automatisch bessere Gesamttrocknung.","Luft/O₂\n════ schnelle Haut (zu viel Primärtrockner)\n~~~~ weicher Unterfilm → Runzeln"],
// LS03 Melamin
[3,"Wie entsteht eine Methylolgruppe am Melamin?",["Ein Melamin-N besitzt ein freies Elektronenpaar beziehungsweise ein nucleophiles N–H-Zentrum.","Das Carbonyl-C von Formaldehyd ist elektrophil.","N greift C an und die C=O-π-Bindung klappt zum O auf.","Nach Protonentransfer entsteht die N–CH₂OH-Methylolgruppe.","Melamin besitzt sechs N–H-Positionen und kann mehrfach methyloliert werden."],"Die Methylolierung ist eine Addition an Formaldehyd, noch keine Vernetzung.","Mel–NH: + H–C(=O)–H\n       N: ↷ C ; π ↷ O\n→ Mel–N⁺H–CH₂–O⁻\n→ Protontransfer → Mel–NH–CH₂OH"],
[3,"Wie erfolgt die Veretherung einer Methylolgruppe?",["Unter Säure wird die Methylol-OH-Gruppe protoniert.","Wasser kann als gute Abgangsgruppe austreten; ein N–CH₂⁺-ähnliches elektrophiles Zentrum entsteht.","Das freie Elektronenpaar des Alkohol-O greift das CH₂-Zentrum an.","Eine protonierte Ethergruppe N–CH₂–O⁺H–R entsteht.","Deprotonierung liefert den Methylolether und regeneriert H⁺."],"Veretherung senkt Polarität und Reaktivität, beseitigt sie aber nicht vollständig.","Mel–N–CH₂–OH + H⁺ → Mel–N–CH₂–OH₂⁺\nC–OH₂ ↷ O → Mel–N–CH₂⁺ + H₂O\nROH :O: ↷ CH₂⁺ → Mel–N–CH₂–O⁺H–R\n→ Mel–N–CH₂–OR + H⁺"],
[3,"Wie vernetzt ein Methylolether mit einem OH-Polymer?",["Säure protoniert den Ether-Sauerstoff beziehungsweise aktiviert die N–CH₂–OR-Gruppe.","Der Alkohol ROH wird als Abgangsgruppe vorbereitet.","Das Polymer-OH greift mit seinem O-Elektronenpaar das elektrophile CH₂ an.","Eine neue Polymer–O–CH₂–Melamin-Etherbrücke entsteht.","Deprotonierung und Alkoholabspaltung schließen die Co-Vernetzung ab."],"Der OH-Angriff erfolgt am Methylol-C, nicht am Melaminring.","Mel–N–CH₂–OR + H⁺ → Mel–N–CH₂–O⁺H–R\nPolymer–OH :O: ↷ CH₂ ; C–ORH⁺ ↷ O\n→ Polymer–O⁺H–CH₂–N–Mel + ROH\n→ Polymer–O–CH₂–N–Mel + H⁺"],
[3,"Was ist HMMM und warum ist es besonders lagerstabil?",["HMMM bedeutet Hexamethoxymethylmelamin.","Alle sechs reaktiven N–H-Positionen sind weitgehend methyloliert und methyliert.","Dadurch fehlen freie NH- und weitgehend freie Methylolgruppen.","Selbstkondensation während Lagerung ist deshalb stark reduziert.","Für die Vernetzung braucht HMMM stärkere Säurekatalyse und höhere Einbrennbedingungen."],"Hohe Veretherung bedeutet bessere Stabilität, aber geringere Reaktivität.","                 N\n              /     \\\n     (MeOCH₂)₂N       N(CH₂OMe)₂\n              \\  N  /\n                 |\n             N(CH₂OMe)₂\n≈ 6 × –CH₂–OCH₃ (HMMM)"],
[3,"Warum können Melaminharze selbst- und co-vernetzen?",["Methylolgruppen können mit NH-Gruppen kondensieren.","Dabei entstehen Methylenbrücken unter Wasserabspaltung.","Zwei Methylolgruppen können Dimethylenetherbrücken bilden.","Methylol-/Ethergruppen können außerdem mit Polymer-OH reagieren.","Das Verhältnis dieser Wege bestimmt Netzwerkstruktur, Witterung und Sprödigkeit."],"Selbstkondensation verbraucht Vernetzer, ohne zwingend zwei Polymerketten zu verbinden.","Mel–NH + HOCH₂–Mel → Mel–N–CH₂–Mel + H₂O\nMel–CH₂OH + HOCH₂–Mel → Mel–CH₂–O–CH₂–Mel + H₂O\nPolymer–OH + Mel–CH₂OR → Polymer–O–CH₂–Mel + ROH"],
// LS04 Acrylate
[4,"Wie erzeugt ein Initiator das erste Kettenradikal?",["Azo- oder Peroxidinitiatoren zerfallen bei definierter Temperatur homolytisch.","Die σ-Bindung wird symmetrisch gespalten; jedes Fragment erhält ein Elektron.","So entstehen zwei Initiatorradikale.","Ein Radikal addiert an die C=C-π-Bindung eines Monomers.","Eine neue C–C-σ-Bindung und ein Monomerradikal am zweiten C entstehen."],"Initiatorzerfall ist endotherm, die anschließende Polymerisation stark exotherm.","RO–OR --Δ→ 2 RO•\nRO• + CH₂=C(R)COOR'\n  RO• ↷ C1 ; π(C=C) ↷ C2\n→ RO–CH₂–C•(R)COOR'"],
[4,"Wie läuft die Propagation eines Acrylatradikals?",["Das Kettenende trägt ein ungepaartes Elektron.","Es greift ein C-Atom der C=C-Doppelbindung eines neuen Monomers an.","Die π-Elektronen bilden am anderen C das neue Radikalzentrum.","Dabei entsteht eine neue C–C-Bindung und die Kette wächst um eine Einheit.","Dieser Vorgang wiederholt sich tausende Male pro Sekunde."],"Das Radikal wird bei der Propagation nicht verbraucht, sondern an das neue Kettenende verschoben.","P–CH₂–C•(R)COOR' + CH₂=C(R)COOR'\n      • ↷ CH₂ ; π ↷ C\n→ P–CH₂–C(R)(COOR')–CH₂–C•(R)COOR'"],
[4,"Wie erfolgt der Kettenabbruch durch Rekombination?",["Zwei wachsende Kettenradikale nähern sich an.","Jedes Radikalzentrum besitzt ein ungepaartes Elektron.","Die beiden Elektronen bilden gemeinsam eine C–C-σ-Bindung.","Der Radikalzustand verschwindet vollständig.","Ein Polymermolekül mit der Summe beider Kettenlängen entsteht."],"Bei Rekombination werden zwei kinetische Ketten zu einem Molekül.","P• + •P' → P–P'"],
[4,"Wie unterscheiden sich Disproportionierung und Kettenübertragung?",["Bei Disproportionierung abstrahiert ein Kettenradikal H von einem zweiten Kettenradikal.","Es entstehen ein gesättigtes und ein ungesättigtes Kettenende.","Bei Kettenübertragung wird H von Lösemittel, Regler oder Polymer abstrahiert.","Die alte Kette endet, aber am Reaktionspartner entsteht ein neues Radikal.","Dieses neue Radikal kann eine weitere Kette starten oder Verzweigung erzeugen."],"Kettenübertragung beendet ein Molekül, nicht zwingend die gesamte Radikalkinetik.","Disproportionierung:\nP–CH₂–CH₂• + •CH–CH₂–P' → P–CH₂–CH₃ + CH=CH–P'\nÜbertragung:\nP• + R–H → P–H + R• ; R• + Monomer → neue Kette"],
[4,"Warum steuert die Dosierung Molmasse und Reaktionswärme?",["Mehr Initiator erzeugt mehr Radikale pro Zeit.","Mehr Radikale starten mehr Ketten und erhöhen die Reaktionsrate.","Das verfügbare Monomer verteilt sich auf mehr Ketten; die mittlere Kettenlänge sinkt.","Gleichzeitig ist jede C=C-Addition exotherm.","Kontrollierte Monomer-/Initiatordosierung begrenzt momentane Wärmefreisetzung und verhindert Trommsdorff-Beschleunigung."],"Hohe Reaktionsgeschwindigkeit und hohe Molmasse steigen nicht automatisch gemeinsam.","[R•] ↑ → vₚ ↑, Kettenzahl ↑, Mₙ ↓\nDosierung → dQ/dt kontrolliert"],
// LS05 Isocyanate
[5,"Wie greift ein Alkohol die Isocyanatgruppe an?",["Das zentrale NCO-C ist durch N und O elektronarm und elektrophil.","Das freie Elektronenpaar des Alkohol-O greift dieses C an.","Die C=N-π-Elektronen werden zum N verschoben; ein tetraedrisches Zwitterion entsteht.","Ein Proton wird vom O⁺ auf N⁻ übertragen.","Die stabile Urethanbindung R–NH–C(=O)–OR' entsteht, ohne Abspaltprodukt."],"Der Angriff erfolgt am NCO-Kohlenstoff, nicht am Isocyanat-Stickstoff.","R–N=C=O + HO:–R'\n:O: ↷ C ; π(C=N) ↷ N\n→ R–N⁻–C(=O)–O⁺H–R'   tetraedr./zwitterionisch\n→ Protontransfer O→N\n→ R–NH–C(=O)–O–R'  (Urethan)"],
[5,"Wie reagiert Wasser mit Isocyanat bis zum Harnstoff?",["Wasser-O greift das elektrophile NCO-C an.","Nach Protonentransfer entsteht instabile Carbaminsäure R–NH–COOH.","Carbaminsäure decarboxyliert zu Amin und CO₂.","Das gebildete Amin greift mit seinem N-Elektronenpaar ein weiteres NCO-C an.","Nach Protonentransfer entsteht eine Harnstoffbindung R–NH–CO–NH–R."],"Ein Mol Wasser kann indirekt zwei NCO-Gruppen verbrauchen.","R–NCO + H₂O:\nH₂O :O: ↷ C(NCO) → R–N⁻–C(=O)–OH₂⁺\n→ R–NH–C(=O)–OH → R–NH₂ + CO₂↑\nR–NH₂: + O=C=N–R\n:N ↷ C ; π(C=N) ↷ N\n→ R–NH–C(=O)–NH–R  (Harnstoff)"],
[5,"Wie katalysiert eine Lewis-Säure die Urethanbildung?",["Eine Lewis-Säure koordiniert an den NCO- oder Alkohol-Sauerstoff.","Dadurch wird entweder das NCO-C elektrophiler oder der Alkohol nucleophiler.","Der aktivierte Alkohol greift schneller am NCO-C an.","Das tetraedrische Zwischenprodukt durchläuft Protonentransfer.","Der Katalysator wird freigesetzt und die Urethanbindung bleibt zurück."],"Katalyse verkürzt Topfzeit; sie verändert die Gleichungsstöchiometrie nicht.","   O→SnR₂\n   |\nR–N=C=O  +  HO–R'  → aktivierter Komplex\n:O(Alkohol) ↷ C(NCO) → Zwischenprodukt → Urethan + Kat."],
[5,"Wie funktioniert die Blockierung eines Isocyanats?",["Ein Blockierungsmittel mit aktivem H addiert an NCO.","Es entsteht eine thermisch spaltbare Urethan- oder ähnliche Schutzgruppe.","Bei Lagerung ist kein freies NCO vorhanden.","Beim Einbrennen verschiebt Wärme das Gleichgewicht und setzt Blocker frei.","Das regenerierte beziehungsweise direkt umgetauschte reaktive Zentrum vernetzt mit Polymer-OH."],"Bei manchen Systemen läuft Umurethanisierung ohne frei messbares NCO als Zwischenstufe.","R–NCO + H–B ⇌ R–NH–C(=O)–B\n                 Lagerung stabil\n--Δ, Polymer–OH→ R–NH–C(=O)–O–Polymer + H–B"],
[5,"Warum wählt man HDI/IPDI für Klarlack und MDI/TDI eher für verdeckte Systeme?",["Aromatische Isocyanate besitzen NCO-Gruppen am aromatischen System.","Sie reagieren meist schneller und sind kostengünstig.","UV erzeugt jedoch chromophore Abbauprodukte und Vergilbung.","Aliphatische HDI-/IPDI-Derivate sind lichtstabiler.","Darum dienen sie sichtbaren Außenflächen, während aromatische Typen etwa in Grundierung oder KTL-Vernetzern liegen."],"Reaktivität, Preis und Witterungsbeständigkeit müssen gemeinsam bewertet werden.","Ar–NCO --UV→ chromophore Produkte (gelb)\nAlkyl–NCO → lichtstabileres Urethan"],
// LS06 PUR
[6,"Warum entsteht aus Diol und Diisocyanat zunächst eine lineare PUR-Kette?",["Beide Reaktionspartner besitzen jeweils Funktionalität zwei.","Jede OH-Gruppe reagiert mit einer NCO-Gruppe.","Nach jedem Schritt bleiben an beiden Seiten reaktive Endgruppen.","So wächst eine Kette stufenweise durch Polyaddition.","Erst Funktionalitäten über zwei erzeugen chemische Verzweigung und Netzwerk."],"Urethangruppen allein bedeuten nicht automatisch einen Duroplasten.","HO–R–OH + OCN–R'–NCO\n→ –[O–R–O–C(=O)–NH–R'–NH–C(=O)]ₙ–"],
[6,"Wie entstehen Hart- und Weichsegmente im PUR?",["Lange flexible Polyole bilden bewegliche Weichsegmente.","Kurze Diisocyanate und Kettenverlängerer erzeugen urethanreiche Hartsegmente.","Urethan-/Harnstoffgruppen bilden starke Wasserstoffbrücken.","Hartsegmente können sich zu physikalischen Domänen zusammenlagern.","Das Verhältnis steuert Elastizität, Festigkeit, Abrieb und Tg."],"Chemische Vernetzung und physikalische Hartsegmentdomänen sind verschieden.","Weich: ~~~~~OH + OCN–[hart]–NCO\n→ ~~~~~OCO–NH–[hart]–NH–COO~~~~~\n             ⋮ H-Brücken ⋮"],
[6,"Warum ist das NCO/OH-Verhältnis ein Äquivalent- und kein Massenverhältnis?",["Ein Molekül kann mehrere OH- oder NCO-Gruppen tragen.","Reaktivität wird durch Anzahl der Gruppen bestimmt.","Äquivalentmasse setzt Masse in Mol reaktiver Gruppen um.","NCO/OH=1 bedeutet gleiche Zahl reaktiver Gruppen.","Massenverhältnis hängt deshalb von Funktionalität und Molekülmasse beider Komponenten ab."],"1:1 nach Gewicht ist nur zufällig stöchiometrisch.","m(Isocyanat)=m(Polyol) × Äquiv.-Masse(NCO-Komponente)/Äquiv.-Masse(OH-Komponente)"],
[6,"Warum endet die Topfzeit vor sichtbarer Gelierung?",["Unmittelbar nach dem Mischen beginnt NCO/OH-Reaktion.","Molmasse und Verzweigung steigen kontinuierlich.","Viskosität und Relaxationszeit werden größer.","Schon vor dem makroskopischen Gelpunkt verschlechtern sich Verlauf und Benetzung.","Die technische Topfzeit endet daher, wenn Verarbeitung oder Filmleistung außerhalb Spezifikation liegt."],"Flüssig bedeutet nicht automatisch noch verwendbar.","Mischen → Mₙ↑ → η↑ → Verlauf↓ → technische Topfzeit → Gelpunkt"],
[6,"Wie wird eine ionisch stabilisierte PUR-Dispersion wasserdispergierbar?",["Ein Polyol mit ionisierbarer Gruppe wird in das Präpolymer eingebaut.","NCO-terminiertes Präpolymer entsteht in organischer Phase.","Carboxylgruppen werden neutralisiert und dadurch hydrophil.","Beim Eintragen in Wasser ordnen sich ionische Gruppen zur Oberfläche.","Kettenverlängerung in Wasser erhöht Molmasse innerhalb der Partikel."],"Das Polymer ist dispergiert, nicht molekular in Wasser gelöst.","NCO–Prepolymer–COOH + Base → –COO⁻\n+ H₂O → Partikel [hydrophob innen | COO⁻ außen]\n+ Diamin → Kettenverlängerung"],
// LS07 Klarlack
[7,"Warum besteht der Automobillack aus mehreren Schichten?",["Metall braucht zuerst Korrosionsschutz.","KTL liefert Haftung und Barriere auch in Hohlräumen.","Füller egalisiert und verbessert Steinschlagverhalten.","Basislack erzeugt Farbe und Effekt.","Klarlack schützt vor UV, Chemikalien und Kratzern und erzeugt Glanz."],"Keine einzelne Schicht maximiert alle Funktionen.","Metall | Phosphat | KTL | Füller | Basislack | Klarlack"],
[7,"Warum kombiniert ein Klarlack Härte und elastische Rückstellung?",["Harte Netzwerke widerstehen Eindringen und plastischer Deformation.","Zu hohe Härte ohne Beweglichkeit führt zu sprödem Bruch.","Elastische Segmente erlauben Rückstellung nach Belastung.","Oberflächenreibung und Netzwerkheterogenität beeinflussen sichtbare Kratzer.","Optimale Kratzbeständigkeit ist daher ein Gleichgewicht, kein Härtemaximum."],"Pendelhärte allein beschreibt Kratzbeständigkeit nicht vollständig.","Indenter ↓\nhart+spröde → Riss\nhart+elastisch → Rückstellung"],
[7,"Wie arbeiten UV-Absorber und HALS zusammen?",["UV-Absorber absorbieren energiereiche Strahlung.","Sie geben Energie strahlungslos als Wärme ab.","Trotzdem entstehende Polymer-Radikale starten Photooxidation.","HALS fangen Radikalzwischenprodukte in einem regenerativen Zyklus ab.","Zusammen schützen sie Klarlack und darunterliegenden Basislack."],"HALS absorbieren nicht primär UV-Licht; beide Additive haben verschiedene Aufgaben.","UV + UVA → Wärme\nPolymer• / ROO• --HALS-Zyklus→ inaktive Produkte"],
[7,"Warum kann Klarlack mit Melamin oder Polyisocyanat vernetzt werden?",["OH-Acrylat liefert gemeinsame Reaktionsstellen.","Melamin-Methylolether reagieren säurekatalysiert beim Einbrennen.","Polyisocyanate addieren direkt an OH und eignen sich für 2K-Systeme.","Melamin erlaubt 1K-Lagerung, kann aber hohe Temperatur und Säure brauchen.","2K-PUR härtet niedriger, besitzt aber begrenzte Topfzeit."],"Gleiche OH-Hauptkomponente bedeutet nicht gleiche Prozessbedingungen.","Acryl–OH + Mel–CH₂OR --H⁺/Δ→ Acryl–O–CH₂–Mel\nAcryl–OH + OCN–R → Acryl–OCO–NH–R"],
[7,"Warum müssen Klarlackprüfungen als Eigenschaftsprofil gelesen werden?",["Glanz bewertet optische Reflexion.","Pendelhärte bewertet einen Teil mechanischer Oberflächenantwort.","Gitterschnitt prüft Haftverbund.","Lösemittel- und Chemikalientests prüfen Netzwerkbeständigkeit.","Bewitterung und Steinschlag zeigen Langzeit- beziehungsweise Systemleistung."],"Ein einzelner guter Messwert kann einen anderen kritischen Ausfall verdecken.","Optik + Härte + Haftung + Chemie + Bewitterung = Freigabeprofil"],
// LS08 Emulsion
[8,"Wie entstehen bei der Emulsionspolymerisation die ersten Polymerpartikel?",["Emulgator bildet oberhalb der CMC Mizellen in Wasser.","Wasserlöslicher Initiator zerfällt in der Wasserphase zu Radikalen.","Ein Radikal addiert wenige gelöste Monomere und wird oligomer.","Das wachsende hydrophobe Oligomerradikal tritt in eine Mizelle ein.","Dort polymerisiert es weiter; die Mizelle wird zum Polymerpartikel."],"Große Monomertröpfchen sind hauptsächlich Reservoir, nicht Hauptreaktor.","Wasserphase: S₂O₈²⁻ --Δ→ 2 SO₄•⁻\nSO₄•⁻ + M → •Mₙ\n\n○○○○○  Mizelle (Tensidköpfe außen)\n  M M     hydrophober Kern\n   ↑ •Mₙ tritt ein\n→ [Polymerkeim]"],
[8,"Wie wächst ein Latexpartikel weiter?",["Monomertröpfchen halten einen großen Monomervorrat.","Monomer löst sich geringfügig in Wasser.","Es diffundiert durch die Wasserphase zu Polymerpartikeln.","Im Partikel trifft es auf das Kettenradikal und wird addiert.","Teilchenzahl bleibt in der Wachstumsphase ungefähr konstant, Teilchendurchmesser steigt."],"Monomertransport und Polymerisationsort müssen getrennt werden.","Monomertröpfchen  MMMMM\n       M löst sich ↓\nWasser: M → → → Latexpartikel [P• + M → P–M•]\nRadius ↑"],
[8,"Warum stabilisiert Emulgator kleine Partikel?",["Kleine Partikel besitzen hohe spezifische Oberfläche und Oberflächenenergie.","Emulgatormoleküle adsorbieren mit hydrophobem Teil am Polymer.","Hydrophile/ionische Köpfe zeigen ins Wasser.","Elektrostatische oder sterische Abstoßung verhindert engen Kontakt.","Fehlt die Barriere, überwiegen van-der-Waals-Kräfte und Partikel koagulieren."],"Zu viel freier Emulgator verschlechtert später Wasserbeständigkeit und Schaum.","Polymerkern — hydrophober Schwanz | ○⁻ Kopf → Wasser\n○⁻  ← Abstoßung →  ○⁻"],
[8,"Wie wird aus Latexpartikeln ein zusammenhängender Film?",["Wasser verdunstet und der Festkörper steigt.","Partikel packen sich dicht und Kapillarkräfte entstehen.","Oberhalb MFFT deformieren die Partikel.","Grenzflächen verschwinden durch Koaleszenz.","Polymerketten interdiffundieren über frühere Partikelgrenzen und geben Kohäsion."],"Trockene Partikelberührung allein ist noch kein belastbarer Film.","○  ○  ○ --H₂O↓→ ○○○ --Deformation→ ⬡⬡⬡\n→ Grenzfläche verschwindet → ━━━━━ kontinuierlicher Film"],
[8,"Wie erzeugt stufenweise Monomerdosierung Core-Shell-Partikel?",["In der ersten Stufe bildet Monomermischung A die Keime beziehungsweise Kerne.","Diese Partikelzahl dient als Saat für die zweite Stufe.","Monomermischung B polymerisiert bevorzugt an bestehenden Partikeln.","Je nach Verträglichkeit und Kinetik bildet B eine Schale oder Domänen.","So lassen sich harte/soft Bereiche und Oberflächeneigenschaften getrennt einstellen."],"Core-Shell ist eine Partikelmorphologie, nicht bloß eine statistische Copolymerzusammensetzung.","Stufe 1: [AAAA] Kern\nStufe 2: B-Monomer + R•\n→ [ B B B ]\n   [ AAA ]   Core–Shell"],
// LS09 Dispersionsfarbe
[9,"Warum ist PVK eine Volumen- und keine Massenkennzahl?",["Pigmente und Füllstoffe besitzen sehr unterschiedliche Dichten.","Masse allein beschreibt deshalb nicht, wie viel Raum sie im Film einnehmen.","Filmstruktur wird durch belegtes Volumen und Bindemittelvolumen bestimmt.","PVK setzt Pigment-/Füllstoffvolumen ins Verhältnis zu allen nichtflüchtigen Volumina.","So lässt sich Porenbildung und Bindemittelbedarf verschiedener Rohstoffe vergleichen."],"Gleiche Gewichtsrezeptur kann wegen Dichteunterschieden völlig andere PVK besitzen.","PVK = V(Pigment + Füllstoff) / [V(Pigment + Füllstoff)+V(Bindemittel)]"],
[9,"Was passiert mikroskopisch beim Überschreiten der KPVK?",["Unterhalb KPVK benetzt Bindemittel Pigmente und füllt Zwischenräume.","An KPVK reicht es gerade für diese Aufgabe.","Oberhalb fehlt Bindemittel für einen Teil der Hohlräume.","Nach Wasserverdunstung bleiben Luftporen zwischen Pigmenten.","Der Film wird matter und streut stärker, verliert aber Kohäsion und Nassabriebfestigkeit."],"KPVK ist ein Strukturübergang, keine einzelne universelle Zahl.","PVK<KPVK: ●~Bindemittel~● (dicht)\nPVK>KPVK: ●  Luft  ● (porös)"],
[9,"Warum kann Luft oberhalb KPVK das Deckvermögen erhöhen?",["Licht trifft auf Grenzflächen mit unterschiedlichem Brechungsindex.","Pigment/Luft und Bindemittel/Luft erzeugen zusätzliche Indexsprünge.","Diese Grenzflächen streuen sichtbares Licht.","Mehr diffuse Rückstreuung verdeckt den Untergrund.","Nass ist Wasser in Poren, der Indexkontrast kleiner; beim Trocknen steigt Dry Hiding."],"Trockenes Deckvermögen durch Poren ist mit schlechterer Nassbeständigkeit erkauft.","n(Pigment) ≠ n(Luft)\nLicht → ●/Luft ↗ ↘ diffuse Streuung → Untergrund verdeckt"],
[9,"Warum braucht eine Dispersionsfarbe Koaleszenzmittel?",["Ein hartes Polymer besitzt möglicherweise MFFT über Verarbeitungstemperatur.","Koaleszenzmittel löst beziehungsweise plastifiziert Partikeloberflächen.","Tg und effektive MFFT sinken vorübergehend.","Partikel deformieren und Ketten interdiffundieren.","Nach Verdunstung des Mittels gewinnt der Film Härte zurück."],"Zu viel Koaleszenzmittel erhöht VOC, Klebrigkeit und frühe Schmutzaufnahme.","Partikel + Koaleszenzmittel → Tg↓ / MFFT↓\n○○○ → deformiert → Film ; Mittel ↑ verdunstet"],
[9,"Warum wird eine Wandfarbenrezeptur in Mahlgut und Auflack getrennt?",["Pigmente benötigen hohe Scherung und Dispergieradditive zur Benetzung.","Zu viel fertige Dispersion in der Mahlphase kann durch Scherung oder Tensidwechsel destabilisieren.","Im Mahlgut werden Wasser, Dispergierer, Entschäumer und Pigmente konzentriert verarbeitet.","Danach wird Polymerdispersion schonend als Auflack zugesetzt.","Rheologie, pH und Konservierung werden abschließend eingestellt."],"Reihenfolge ist Teil der Kolloidstabilität, nicht nur Mischlogistik.","Mahlgut: H₂O + Dispergierer + Pigment --Scherung→ Dispersion\n+ Bindemitteldispersion (schonend)\n+ Verdicker/Additive → Wandfarbe"],
// LS10 Epoxid
[10,"Wie öffnet ein primäres Amin den Epoxidring?",["Das Amin-N besitzt ein freies Elektronenpaar und ist nucleophil.","Es greift bevorzugt das weniger sterisch gehinderte Epoxid-C an.","Gleichzeitig wird die C–O-Ringbindung zum O gespalten.","Ein Alkoxid/Ammonium-Zwitterion entsteht.","Protonentransfer vom N zum O liefert ein β-Hydroxy-sekundäres Amin."],"Der neu gebildete OH-Rest bleibt im Produkt und beeinflusst Haftung sowie Folgereaktionen.","       O                         O⁻\n      / \\        :NH₂–R ↷ C     |\nR'–CH–CH₂  ----------------→ R'–CH–CH₂–N⁺H₂–R\n C–O ↷ O\n→ Protontransfer N–H ↷ O\n→ R'–CH(OH)–CH₂–NH–R"],
[10,"Wie entsteht durch Amine ein Epoxidnetzwerk?",["Ein primäres Amin besitzt zwei N–H-Wasserstoffe.","Nach erster Ringöffnung entsteht ein sekundäres Amin mit weiterem N–H.","Dieses kann eine zweite Epoxidgruppe öffnen.","Polyamine besitzen mehrere Aminstellen und Epoxidharze mehrere Epoxidringe.","Wiederholte Ringöffnung verbindet viele Harzmoleküle zu einem Netzwerk."],"Ein Amin-H ist ein Äquivalent; ein primäres –NH₂ liefert meist zwei aktive H.","Epoxy–E + H₂N–R–NH₂ + E–Epoxy\n→ Epoxy–CH(OH)–CH₂–NH–R–NH–CH₂–CH(OH)–Epoxy\n                         ↓ weitere E\n                       Netzwerk"],
[10,"Wie wird BADGE aus Bisphenol A und Epichlorhydrin gebildet?",["Phenolische OH-Gruppen von BPA werden basisch zu Phenolaten aktiviert.","Phenolat-O greift Epichlorhydrin nucleophil an.","Zunächst entsteht ein Chlorhydrin-Ether.","Base deprotoniert dessen OH-Gruppe.","Intramolekulare SN2-Abspaltung von Cl⁻ schließt den Epoxidring; beide BPA-OH werden glycidyliert."],"Epichlorhydrin liefert den Glycidylether; das Epoxid entsteht durch Dehydrohalogenierung/Ringschluss.","BPA–O:⁻ + Cl–CH₂–CH–CH₂\n                         \\O/\n→ BPA–O–CH₂–CH(OH)–CH₂Cl  (Chlorhydrin)\nBase: O⁻ ↷ CH₂–Cl ; C–Cl ↷ Cl⁻\n→ BPA–O–CH₂–CH–CH₂\n                 \\O/      (Glycidylether/BADGE)"],
[10,"Warum braucht man EEW und Amin-H-Äquivalent?",["Epoxidharze unterscheiden sich in Epoxidgehalt und Molmasse.","EEW gibt Gramm Harz pro Mol Epoxidgruppe an.","Härter unterscheiden sich in Zahl reaktiver Amin-H.","AHEW gibt Gramm Härter pro Mol aktivem H an.","Nur über Äquivalente erhält jede Epoxidgruppe den vorgesehenen Reaktionspartner."],"1:1 nach Masse ist bei Epoxid/Amin fast nie stöchiometrisch.","m(Härter) = m(Harz) × AHEW / EEW"],
[10,"Warum haftet Epoxid gut, ist aber als Außenklarlack schwach?",["Epoxid- und entstehende OH-Gruppen sind polar und wechselwirken mit Substraten.","Das dichte Netzwerk reduziert Diffusion von Wasser, Ionen und Chemikalien.","Aromatische BPA-Segmente erhöhen Härte und Barriere.","Dieselben aromatischen Strukturen absorbieren UV und bauen photochemisch ab.","Daher nutzt man Epoxid für Grundierung/Korrosionsschutz, nicht als dauerhaft sichtbaren Außenklarlack."],"Gute chemische Barriere ist nicht gleich gute Photooxidationsbeständigkeit.","Substrat ⇄ OH / Ether (Haftung)\nAromat-Netzwerk = Barriere\nAr --UV/O₂→ Radikale → Kreidung / Vergilbung"]
];
window.LEARNING_DATA.whyChains=WC.map((x,i)=>({id:`wc-${x[0]}-${i}`,ls:x[0],t:x[1],steps:x[2],trap:x[3],mechanism:x[4],source:`LS${String(x[0]).padStart(2,"0")} 课件机理整理`}));
